{{- if and .Values.keycloak.enabled .Values.keycloak.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ipam.keycloakFullname" . }}
  labels:
    {{- include "ipam.keycloakLabels" . | nindent 4 }}
  {{- with .Values.keycloak.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.keycloak.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.keycloak.ingress.tls }}
  tls:
    {{- range .Values.keycloak.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.keycloak.ingress.host }}
    - host: {{ .Values.keycloak.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.keycloak.ingress.path }}
            pathType: {{ .Values.keycloak.ingress.pathType }}
            backend:
              service:
                name: {{ include "ipam.keycloakFullname" . }}
                port:
                  number: {{ .Values.keycloak.service.port }}
    {{- else }}
    - http:
        paths:
          - path: {{ .Values.keycloak.ingress.path }}
            pathType: {{ .Values.keycloak.ingress.pathType }}
            backend:
              service:
                name: {{ include "ipam.keycloakFullname" . }}
                port:
                  number: {{ .Values.keycloak.service.port }}
    {{- end }}
{{- end }}
