{{- if .Values.keycloak.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipam.keycloakFullname" . }}
  labels:
    {{- include "ipam.keycloakLabels" . | nindent 4 }}
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - port: {{ .Values.keycloak.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ipam.keycloakSelectorLabels" . | nindent 4 }}
{{- end }}
