{{- if and (not .Values.db.existingSecret) .Values.db.connString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipam.fullname" . }}-db
  labels:
    {{- include "ipam.labels" . | nindent 4 }}
type: Opaque
data:
  DB_CONN: {{ .Values.db.connString | b64enc }}
{{- end }}
