apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipam.feFullname" . }}
  labels:
    {{- include "ipam.feLabels" . | nindent 4 }}
spec:
  type: {{ .Values.fe.service.type }}
  ports:
    - port: {{ .Values.fe.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ipam.feSelectorLabels" . | nindent 4 }}
